urdf_path: "./x7_without_coll.urdf"
# srdf_path: "./rm65.srdf"
joint_stiffness: 1000
joint_damping: 200
gripper_stiffness: 1000
gripper_damping: 200
move_group: ["arm_l_link7_1","arm_r_link_7_1"]
ee_joints: ["arm_joint_l_7", "arm_joint_r_7"]
arm_joints_name: [["arm_joint_l_1", "arm_joint_l_2", "arm_joint_l_3", "arm_joint_l_4", "arm_joint_l_5", "arm_joint_l_6", "arm_joint_l_7"], 
                  ["body_joint_1", "arm_joint_r_1", "arm_joint_r_2", "arm_joint_r_3", "arm_joint_r_4", "arm_joint_r_5", "arm_joint_r_6", "arm_joint_r_7"]]
gripper_name:
  - base: "catch_joint_l_1"
    mimic: 
      - ["catch_joint_l_2", -1, 0.]
  - base: "catch_joint_r_1"
    mimic: 
      - ["catch_joint_r_2", -1, 0.]
gripper_bias: 0.12
gripper_scale: [0.0, 0.04765]
homestate: [[0.01,0,0,0,0,0,0,0], [0.01,0,0,0,0,0,0,0]]
delta_matrix: [[1,0,0],[0,-1,0],[0,0,-1]]
global_trans_matrix: [[0,0,1],[0,1,0],[-1,0,0]]
robot_pose: [[0.0, -0.65, 0.2, 0.707, 0.0, 0.0, 0.707]]
# planner: "mplib_screw"
planner: "curobo"
dual_arm: True
rotate_lim: [0, 1]
grasp_perfect_direction: ['front_right', 'front_left']
static_camera_list: 
- name: head_camera
  type: D435
  position:
  - -0.032
  - -0.45
  - 1.35
  forward:
  - 0
  - 0.6
  - -0.8
  left:
  - -1
  - 0
  - 0
- name: front_camera
  type: D435
  position:
  - 0
  - -0.45
  - 0.85
  forward:
  - 0
  - 1
  - -0.1
  left:
  - -1
  - 0
  - 0