collision_spheres:
  base_link0:
    - "center": [-0.0, -0.05, -0.116]
      "radius": 0.1
    - "center": [-0.226, -0.073, -0.125]
      "radius": 0.1
    - "center": [0.125, -0.206, -0.09]
      "radius": 0.1
    - "center": [0.093, 0.14, -0.097]
      "radius": 0.1
    - "center": [-0.1, -0.043, -0.177]
      "radius": 0.1
    - "center": [-0.1, -0.043, -0.277]
      "radius": 0.1
    - "center": [-0.1, -0.036, -0.337]
      "radius": 0.1
    - "center": [-0.1, -0.037, -0.493]
      "radius": 0.1
    - "center": [-0.1, -0.036, -0.67]
      "radius": 0.1
    - "center": [-0.1, -0.036, -0.737]
      "radius": 0.1
    - "center": [-0.1, -0.036, -0.807]
      "radius": 0.1
    - "center": [-0.1, -0.045, -0.934]
      "radius": 0.1
    - "center": [-0.1, -0.039, -1.139]
      "radius": 0.1
  body_link2_1:
    - "center": [0.168, -0.078, -0.491]
      "radius": 0.05
  arm_l_link1_1:
    - "center": [0.021, -0.027, 0.0]
      "radius": 0.02
  arm_l_link2_1:
    - "center": [-0.029, 0.0, -0.0]
      "radius": 0.03
  arm_l_link3_1:
    - "center": [-0.0, 0.0, 0.045]
      "radius": 0.04
  arm_l_link4_1:
    - "center": [0.068, -0.025, 0.0]
      "radius": 0.03
  arm_l_link5_1:
    - "center": [0.093, 0.0, -0.0]
      "radius": 0.03
  arm_l_link6_1:
    - "center": [0.047, -0.022, 0.0]
      "radius": 0.04
  arm_l_link7_1:
    - "center": [0.071, -0.001, -0.02]
      "radius": 0.03
    - "center": [0.106, -0.078, -0.02]
      "radius": 0.01
    - "center": [0.105, -0.051, -0.017]
      "radius": 0.01
    - "center": [0.108, 0.074, -0.02]
      "radius": 0.01
    - "center": [0.105, 0.05, -0.016]
      "radius": 0.01
  catch_1_2:
    - "center": [0.021, -0.065, 0.007]
      "radius": 0.01
    - "center": [0.064, -0.075, 0.005]
      "radius": 0.01
  catch_2_2:
    - "center": [0.021, 0.067, 0.009]
      "radius": 0.01
    - "center": [0.05, 0.073, 0.006]
      "radius": 0.01
  arm_r_link1_1:
    - "center": [0.024, 0.044, 0.0]
      "radius": 0.02
  arm_r_link2_1:
    - "center": [-0.019, 0.015, 0.016]
      "radius": 0.05
  arm_r_link3_1:
    - "center": [-0.004, -0.0, 0.191]
      "radius": 0.03
    - "center": [0.024, -0.0, 0.064]
      "radius": 0.03
  arm_r_link4_1:
    - "center": [0.058, 0.026, 0.006]
      "radius": 0.04
  arm_r_link5_1:
    - "center": [0.093, -0.0, 0.001]
      "radius": 0.04
  arm_r_link6_1:
    - "center": [0.053, 0.025, 0.0]
      "radius": 0.04
  arm_r_link7_1:
    - "center": [0.07, -0.001, -0.022]
      "radius": 0.03
    - "center": [0.108, -0.075, -0.019]
      "radius": 0.01
    - "center": [0.107, -0.054, -0.019]
      "radius": 0.01
    - "center": [0.106, 0.072, -0.018]
      "radius": 0.01
    - "center": [0.103, 0.047, -0.016]
      "radius": 0.01
  catch_1_1:
    - "center": [0.024, -0.066, 0.01]
      "radius": 0.01
    - "center": [0.052, -0.073, 0.005]
      "radius": 0.01
  catch_2_1:
    - "center": [0.016, 0.065, 0.012]
      "radius": 0.01
    - "center": [0.041, 0.071, 0.012]
      "radius": 0.01